---
server:
  port: 9001
logging:
  level:
    org:
      apache:
        coyote:
          http11: WARN
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
registry_service:
  url: https://demo4460370.mockable.io/registry/
  retry:
    max_attempts: 3
    initial_interval_in_millis: 1000
    interval_multiplier: 1.0
  cache:
    expiry_cron_schedule: "0 */5 * * * *"
  timeouts:
    connection_in_seconds: 10
    read_in_seconds: 10
    write_in_seconds: 10
bpp_registry_service:
  url: https://demo4460370.mockable.io/bpp_registry/
gateway_service:
  retry:
    max_attempts: 3
    initial_interval_in_millis: 1000
    interval_multiplier: 1.0
  timeouts:
    connection_in_seconds: 10
    read_in_seconds: 10
    write_in_seconds: 10
bpp_service:
  retry:
    max_attempts: 3
    initial_interval_in_millis: 1000
    interval_multiplier: 1.0
  timeouts:
    connection_in_seconds: 10
    read_in_seconds: 10
    write_in_seconds: 10
protocol_service:
  url: http://localhost:9002/
  retry:
    max_attempts: 3
    initial_interval_in_millis: 1000
    interval_multiplier: 1.0
  timeouts:
    connection_in_seconds: 5
    read_in_seconds: 5
    write_in_seconds: 5
context:
  domain: nic2004:52110
  city: std:080
  country: IND
  bap_id: box.beckn.org
  bap_uri: http://localhost:9002/protocol/v1
  ttl_seconds: 20
beckn:
  security.enabled: false
security:
  self:
    private_key:
    unique_key_id: key1
  firebase-props:
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  allow-credentials: true
  allowed-origins:
    - http://localhost:9001
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/**
  exposed-headers:
    - X-Xsrf-Token
  protected-actions:
    - /**/select
    - /**/initialize_order
    - /**/on_initialize_order
    - /**/confirm_order
    - /**/on_confirm_order
    - /**/get_quote
    - /**/on_get_quote
    - /**/orders
    - /**/on_rating
    - /**/rating
    - /**/update
    - /**/cancel_order
    - /**/on_cancel_order
    - /**/on_track
    - /**/track
    - /**/on_order_status
    - /**/order_status
    - /**/delivery_address
    - /**/confirm_order
    - /**/billing_details
    - /**/account_details
    - /**/on_support
    - /**/get_support
database:
  mongo:
    url: mongodb://localhost:27017
    name: sandbox_client
management:
  endpoints:
    web:
      exposure:
        include: "configprops, env, health, loggers, metrics, mappings, httptrace"